package macos_configuration_profiles

// ResponseCustomSettingsSchemaList represents the top-level response for custom settings schema list.
// It is a slice of buckets, each containing custom settings domains.
type ResponseCustomSettingsSchemaList []ResourceCustomSettingsBucket

// ResourceCustomSettingsBucket represents a single bucket of custom settings schemas.
type ResourceCustomSettingsBucket struct {
	BucketName            string                                  `json:"bucketName"`
	DisplayName           string                                  `json:"displayName"`
	CustomSettingsDomains map[string]ResourceCustomSettingsDomain `json:"customSettingsDomains"`
}

// ResourceCustomSettingsDomain represents a domain of custom settings.
type ResourceCustomSettingsDomain struct {
	SettingsDomain string                           `json:"settingsDomain"`
	Versions       map[string]ResourceDomainVersion `json:"versions"`
}

// ResourceDomainVersion represents a specific version of a domain.
type ResourceDomainVersion struct {
	Version  string   `json:"version"`
	Variants []string `json:"variants"`
}

// ResourceConfigProfile represents a macOS configuration profile.
type ResourceConfigProfile struct {
	// PayloadUUID is assigned by the server on create. It is ignored in
	// update request bodies, where the path parameter wins.
	PayloadUUID string `json:"payloadUUID"`

	PayloadContent []PayloadContentItem `json:"payloadContent"`

	// Level must be ConfigProfileLevelSystem or ConfigProfileLevelUser.
	// Write-only: accepted on create and update, never present in GET
	// responses. See enum.go for why the title-case forms are rejected.
	Level string `json:"level,omitempty"`
}

// PayloadContentItem represents an item in the payload content.
type PayloadContentItem struct {
	// PayloadType must be one of an undocumented server-side allowlist; see
	// the package documentation. Unsupported values return HTTP 400
	// INVALID_FIELD "Provide a proper payloadType field".
	PayloadType    string `json:"payloadType"`
	PayloadVersion int    `json:"payloadVersion"`

	PayloadIdentifier string `json:"payloadIdentifier"`

	// PayloadUUID is generated by the server when omitted.
	PayloadUUID string `json:"payloadUUID"`

	// PayloadOrganization defaults to "JAMF Software" when omitted.
	PayloadOrganization string `json:"payloadOrganization,omitempty"`

	// PreferenceDomain is required by PayloadTypeManagedClientPreferences
	// payloads despite the omitempty tag; omitting it there returns HTTP 400
	// INVALID_CONTENT "must not be blank". Other payload types do not need it.
	PreferenceDomain string `json:"preferenceDomain,omitempty"`

	Forced *ForcedSettings `json:"forced,omitempty"`

	// PayloadDisplayName defaults to "Custom Settings" when omitted.
	PayloadDisplayName string `json:"payloadDisplayName,omitempty"`
}

// ForcedSettings represents forced settings in a payload.
type ForcedSettings struct {
	// Plist is required whenever Forced is non-nil, and must be a complete
	// plist document -- <?xml ...?><plist version="1.0"><dict>...</dict></plist>.
	// A bare <dict>...</dict> fragment is rejected with HTTP 400
	// INVALID_CONTENT "Couldn't map content". The schema reference fields
	// below do not substitute for it.
	Plist         string `json:"plist,omitempty"`
	JsonSchema    string `json:"jsonSchema,omitempty"`
	SchemaSource  string `json:"schemaSource,omitempty"`
	SchemaDomain  string `json:"schemaDomain,omitempty"`
	SchemaVersion string `json:"schemaVersion,omitempty"`
	SchemaVariant string `json:"schemaVariant,omitempty"`
}

// ResponseConfigProfileCreate represents the response when creating a
// configuration profile. Update returns this same shape.
type ResponseConfigProfileCreate struct {
	UUID string `json:"uuid"`
}
