package constants

// ============================================================================
// Jamf Pro API Endpoints
// ============================================================================
// Jamf Pro API documentation: https://developer.jamf.com/jamf-pro/docs

const (
	EndpointJamfProAccessManagementSettingsV4                = "/api/v4/enrollment/access-management"
	EndpointJamfProAccountPreferencesV3                      = "/api/v3/account-preferences"
	EndpointJamfProAccountsV1                                = "/api/v1/accounts"
	EndpointJamfProActivationCodeV1                          = "/api/v1/activation-code"
	EndpointJamfProActivationCodeOrganizationNameV1          = "/api/v1/activation-code/organization-name"
	EndpointJamfProActivationCodeHistoryV1                   = "/api/v1/activation-code/history"
	EndpointJamfProActivationCodeHistoryExportV1             = "/api/v1/activation-code/history/export"
	EndpointJamfProAdcsSettingsV1                            = "/api/v1/pki/adcs-settings"
	EndpointJamfProAdvancedMobileDeviceSearchesV1            = "/api/v1/advanced-mobile-device-searches"
	EndpointJamfProAdvancedUserContentSearchesV1             = "/api/v1/advanced-user-content-searches"
	EndpointJamfProADUESessionTokenSettingsV1                = "/api/v1/adue-session-token-settings"
	EndpointJamfProAuthV1                                    = "/api/v1/auth"
	EndpointJamfProApiIntegrationsV1                         = "/api/v1/api-integrations"
	EndpointJamfProAPIRolePrivilegesV1                       = "/api/v1/api-role-privileges"
	EndpointJamfProAPIRolesV1                                = "/api/v1/api-roles"
	EndpointJamfProAPNSClientPushStatusV1                    = "/api/v1/apns-client-push-status"
	EndpointJamfProEnableAllClientsV1                        = "/api/v1/apns-client-push-status/enable-all-clients"
	EndpointJamfProEnableAllClientsStatusV1                  = "/api/v1/apns-client-push-status/enable-all-clients/status"
	EndpointJamfProEnableClientV1                            = "/api/v1/apns-client-push-status/enable-client"
	EndpointJamfProAppInstallersV1                           = "/api/v1/app-installers"
	EndpointJamfProAppInstallersTitlesV1                     = "/api/v1/app-installers/titles"
	EndpointJamfProAppInstallersDeploymentsV1                = "/api/v1/app-installers/deployments"
	EndpointJamfProFormInputFieldsV1                         = "/api/v1/app-request/form-input-fields"
	EndpointJamfProAppRequestSettingsV1                      = "/api/v1/app-request/settings"
	EndpointJamfProAppStoreCountryCodesV1                    = "/api/v1/app-store-country-codes"
	EndpointJamfProBookmarksV1                               = "/api/v1/bookmarks"
	EndpointJamfProBrandingImagesDownloadV1                  = "/api/v1/branding-images/download"
	EndpointJamfProBuildingsV1                               = "/api/v1/buildings"
	EndpointJamfProCacheSettingsV1                           = "/api/v1/cache-settings"
	EndpointJamfProCategoriesV1                              = "/api/v1/categories"
	EndpointJamfProCertificateAuthorityV1                    = "/api/v1/pki/certificate-authority"
	EndpointJamfProClassicLdapV1                             = "/api/v1/classic-ldap"
	EndpointJamfProClientCheckinV3                           = "/api/v3/check-in"
	EndpointJamfProClientCheckinHistoryV3                    = "/api/v3/check-in/history"
	EndpointJamfProCloudAzureV1                              = "/api/v1/cloud-azure"
	EndpointJamfProCloudDistributionPointV1                  = "/api/v1/cloud-distribution-point"
	EndpointJamfProCloudDistributionPointHistoryV1           = "/api/v1/cloud-distribution-point/history"
	EndpointJamfProCloudDistributionPointFilesV1             = "/api/v1/cloud-distribution-point/files"
	EndpointJamfProCloudDistributionPointFailUploadV1        = "/api/v1/cloud-distribution-point/fail-upload"
	EndpointJamfProCloudDistributionPointRefreshV1           = "/api/v1/cloud-distribution-point/refresh-inventory"
	EndpointJamfProCloudIdpV1                                = "/api/v1/cloud-idp"
	EndpointJamfProCloudInformationV1                        = "/api/v1/cloud-information"
	EndpointJamfProCloudLdapV2                               = "/api/v2/cloud-ldaps"
	EndpointJamfProCloudLdapKeystoreV1                       = "/api/v1/ldap-keystore/verify"
	EndpointJamfProComputerExtensionAttributesV1             = "/api/v1/computer-extension-attributes"
	EndpointJamfProComputerGroupsV1                          = "/api/v1/computer-groups"
	EndpointJamfProSmartComputerGroupsV2                     = "/api/v2/computer-groups/smart-groups"
	EndpointJamfProSmartComputerGroupMembershipV2            = "/api/v2/computer-groups/smart-group-membership"
	EndpointJamfProStaticComputerGroupsV2                    = "/api/v2/computer-groups/static-groups"
	EndpointJamfProComputerInventoryV3                       = "/api/v3/computers-inventory"
	EndpointJamfProComputerInventoryV1                       = "/api/v1/computer-inventory"
	EndpointJamfProComputerInventoryCollectionSettingsV2     = "/api/v2/computer-inventory-collection-settings"
	EndpointJamfProComputerPrestagesV2                       = "/api/v2/computer-prestages"
	EndpointJamfProComputerPrestagesV3                       = "/api/v3/computer-prestages"
	EndpointJamfProConditionalAccessV1                       = "/api/v1/conditional-access"
	EndpointJamfProCSAV1                                     = "/api/v1/csa/token"
	EndpointJamfProDeclarativeDeviceManagementV1             = "/api/v1/ddm"
	EndpointJamfProDepartmentsV1                             = "/api/v1/departments"
	EndpointJamfProDeviceCommunicationSettingsV1             = "/api/v1/device-communication-settings"
	EndpointJamfProDeviceCommunicationSettingsHistoryV1      = "/api/v1/device-communication-settings/history"
	EndpointJamfProDeviceEnrollmentsV1                       = "/api/v1/device-enrollments"
	EndpointJamfProDevicesV1                                 = "/api/v1/devices"
	EndpointJamfProTrustLifecycleManagerV1                   = "/api/v1/pki/digicert/trust-lifecycle-manager"
	EndpointJamfProDistributionPointsV1                      = "/api/v1/distribution-points"
	EndpointJamfProDistributionPointsDeleteMultipleV1        = "/api/v1/distribution-points/delete-multiple"
	EndpointJamfProDockItemsV1                               = "/api/v1/dock-items"
	EndpointJamfProDSSDeclarationsV1                         = "/api/v1/dss-declarations"
	EndpointJamfProEbooksV1                                  = "/api/v1/ebooks"
	EndpointJamfProEngageV2                                  = "/api/v2/engage"
	EndpointJamfProEnrollmentV2                              = "/api/v2/enrollment"
	EndpointJamfProEnrollmentV3                              = "/api/v3/enrollment"
	EndpointJamfProEnrollmentV4                              = "/api/v4/enrollment"
	EndpointJamfProEnrollmentCustomizationPreviewV1          = "/api/v1/enrollment-customization"
	EndpointJamfProEnrollmentCustomizationsV2                = "/api/v2/enrollment-customizations"
	EndpointJamfProEnrollmentCustomizationsImagesV2          = "/api/v2/enrollment-customizations/images"
	EndpointJamfProEnrollmentSettingsV4                      = "/api/v4/enrollment"
	EndpointJamfProGroupsV1                                  = "/api/v1/groups"
	EndpointJamfProGSXConnectionV1                           = "/api/v1/gsx-connection"
	EndpointJamfProHealthCheckV1                             = "/api/v1/health-check"
	EndpointJamfProHealthStatusV1                            = "/api/v1/health-status"
	EndpointJamfProIconV1                                    = "/api/v1/icon"
	EndpointJamfProIconsDownloadV1                           = "/api/v1/icon/download"
	EndpointJamfProImpactAlertNotificationSettingsV1         = "/api/v1/impact-alert-notification-settings"
	EndpointJamfProInventoryInformationV1                    = "/api/v1/inventory-information"
	EndpointJamfProInventoryPreloadV2                        = "/api/v2/inventory-preload"
	EndpointJamfProJamfAccountPreferencesV3                  = "/api/v3/account-preferences"
	EndpointJamfProJamfConnectV1                             = "/api/v1/jamf-connect"
	EndpointJamfProJamfManagementFrameworkV1                 = "/api/v1/jamf-management-framework"
	EndpointJamfProJamfPackageV1                             = "/api/v1/jamf-package"
	EndpointJamfProJamfPackageV2                             = "/api/v2/jamf-package"
	EndpointJamfProJamfProInformationV2                      = "/api/v2/jamf-pro-information"
	EndpointJamfProNotificationsV1                           = "/api/v1/notifications"
	EndpointJamfProJamfProServerURLV1                        = "/api/v1/jamf-pro-server-url"
	EndpointJamfProSystemInitialize                          = "/api/v1/system/initialize"
	EndpointJamfProInitializeDatabaseConnection              = "/api/v1/system/initialize-database-connection"
	EndpointJamfProSystemPlatformInitializeV1                = "/api/v1/system/platform-initialize"
	EndpointJamfProUserPreferencesSettingsV1                 = "/api/v1/user/preferences/settings"
	EndpointJamfProUserPreferencesV1                         = "/api/v1/user/preferences"
	EndpointJamfProJamfProVersionV1                          = "/api/v1/jamf-pro-version"
	EndpointJamfProJamfProtectV1                             = "/api/v1/jamf-protect"
	EndpointJamfProJamfProtectRegisterV1                     = "/api/v1/jamf-protect/register"
	EndpointJamfProJamfProtectPlansV1                        = "/api/v1/jamf-protect/plans"
	EndpointJamfProJamfProtectHistoryV1                      = "/api/v1/jamf-protect/history"
	EndpointJamfProJamfProtectDeploymentsV1                  = "/api/v1/jamf-protect/deployments"
	EndpointJamfProSessionV1                                 = "/api/v1/jamf-remote-assist/session"
	EndpointJamfProSessionV2                                 = "/api/v2/jamf-remote-assist/session"
	EndpointJamfProJCDSV1                                    = "/api/v1/jcds"
	EndpointJamfProLdapGroupsV1                              = "/api/v1/ldap/groups"
	EndpointJamfProLdapServersV1                             = "/api/v1/ldap/servers"
	EndpointJamfProLdapServersOnlyV1                         = "/api/v1/ldap/ldap-servers"
	EndpointJamfProLocalAdminPasswordV2                      = "/api/v2/local-admin-password"
	EndpointJamfProLocalesV1                                 = "/api/v1/locales"
	EndpointJamfProLogFlushingV1                             = "/api/v1/log-flushing"
	EndpointJamfProLoginCustomizationV1                      = "/api/v1/login-customization"
	EndpointJamfProConfigProfilesMacOS                       = "/api/config-profiles/macos"
	EndpointJamfProCustomSettingsSchemaList                  = "/api/config-profiles/macos/custom-settings/v1/schema-list"
	EndpointJamfProManagedSoftwareUpdates                    = "/api/v1/managed-software-updates"
	EndpointJamfProBlankPush                                 = "/api/v2/mdm/blank-push"
	EndpointJamfProCommands                                  = "/api/v2/mdm/commands"
	EndpointJamfProDeployPackage                             = "/api/v1/deploy-package"
	EndpointJamfProProfileRenewal                            = "/api/v1/mdm/renew-profile"
	EndpointJamfProDeviceCommonDetailsV1                     = "/api/v1/mdm-renewal/device-common-details"
	EndpointJamfProRenewalStrategiesV1                       = "/api/v1/mdm-renewal/renewal-strategies"
	EndpointJamfProMobileDeviceAppsV1                        = "/api/v1/mobile-device-apps"
	EndpointJamfProMobileDeviceEnrollmentProfileV1           = "/api/v1/mobile-device-enrollment-profile"
	EndpointJamfProMobileDeviceExtensionAttributesV1         = "/api/v1/mobile-device-extension-attributes"
	EndpointJamfProMobileDeviceGroupsV1                      = "/api/v1/mobile-device-groups"
	EndpointJamfProSmartMobileDeviceGroupsV1                 = "/api/v1/mobile-device-groups/smart-groups"
	EndpointJamfProStaticMobileDeviceGroupsV1                = "/api/v1/mobile-device-groups/static-groups"
	EndpointJamfProStaticMobileDeviceGroupMembershipV1       = "/api/v1/mobile-device-groups/static-group-membership"
	EndpointJamfProSmartMobileDeviceGroupMembershipV1        = "/api/v1/mobile-device-groups/smart-group-membership"
	EndpointJamfProMobileDevicePrestagesV2                   = "/api/v2/mobile-device-prestages"
	EndpointJamfProMobileDevicePrestagesV3                   = "/api/v3/mobile-device-prestages"
	EndpointJamfProNotifications2V1                          = "/api/v1/notifications"
	EndpointJamfProOAuth2SessionTokensV1                     = "/api/v1/oauth2/session-tokens"
	EndpointJamfProOIDCV1                                    = "/api/v1/oidc"
	EndpointJamfProOIDCV2                                    = "/api/v2/oidc"
	EndpointJamfProOnboardingV1                              = "/api/v1/onboarding"
	EndpointJamfProEligibleApps                              = "/api/v1/onboarding/eligible-apps"
	EndpointJamfProEligibleConfigurationProfiles             = "/api/v1/onboarding/eligible-configuration-profiles"
	EndpointJamfProEligiblePolicies                          = "/api/v1/onboarding/eligible-policies"
	EndpointJamfProPackagesV1                                = "/api/v1/packages"
	EndpointJamfProPackagesExport                            = "/api/v1/packages/export"
	EndpointJamfProPackagesHistoryExport                     = "/history/export"
	EndpointJamfProPatchManagementAcceptDisclaimerV2         = "/api/v2/patch-management-accept-disclaimer"
	EndpointJamfProPatchPoliciesV2                           = "/api/v2/patch-policies"
	EndpointJamfProPatchPoliciesPolicyDetails                = "/api/v2/patch-policies/policy-details"
	EndpointJamfProPatchSoftwareTitleConfigurationsV2        = "/api/v2/patch-software-title-configurations"
	EndpointJamfProPolicyPropertiesV1                        = "/api/v1/policy-properties"
	EndpointJamfProReenrollmentV1                            = "/api/v1/reenrollment"
	EndpointJamfProReenrollmentHistoryV1                     = "/api/v1/reenrollment/history"
	EndpointJamfProReenrollmentHistoryExport                 = "/api/v1/reenrollment/history/export"
	EndpointJamfProReturnToServiceV1                         = "/api/v1/return-to-service"
	EndpointJamfProScriptsV1                                 = "/api/v1/scripts"
	EndpointJamfProSelfServiceBrandingMobileV1               = "/api/v1/self-service/branding/ios"
	EndpointJamfProSelfServiceBrandingMacOSV1                = "/api/v1/self-service/branding/macos"
	EndpointJamfProBrandingImages                            = "/api/self-service/branding/images"
	EndpointJamfProSelfServicePlusSettingsV1                 = "/api/v1/self-service-plus/settings"
	EndpointJamfProSelfServicePlusFeatureToggleEnabledV1     = "/api/v1/self-service-plus/feature-toggle/enabled"
	EndpointJamfProSelfServiceSettingsV1                     = "/api/v1/self-service/settings"
	EndpointJamfProSelfServiceSettingsHistoryV1              = "/api/v1/self-service/settings/history"
	EndpointJamfProWellKnownSettingsV1                       = "/api/v1/service-discovery-enrollment/well-known-settings"
	EndpointJamfProSitesV1                                   = "/api/v1/sites"
	EndpointJamfProSLASAV1                                   = "/api/v1/slasa"
	EndpointJamfProComputerGroupsBaseV2                      = "/api/v2/computer-groups"
	EndpointJamfProSmartComputerGroups2V2                    = "/api/v2/computer-groups/smart-groups"
	EndpointJamfProSmartComputerGroupMembership2V2           = "/api/v2/computer-groups/smart-group-membership"
	EndpointJamfProSmartMobileDeviceGroups2V2                = "/api/v2/mobile-device-groups/smart-groups"
	EndpointJamfProSmartMobileDeviceGroupMembership          = "/api/v2/mobile-device-groups/smart-group-membership"
	EndpointJamfProSMTPServerV2                              = "/api/v2/smtp-server"
	EndpointJamfProSMTPServerHistoryV1                       = "/api/v1/smtp-server/history"
	EndpointJamfProSMTPServerTestV1                          = "/api/v1/smtp-server/test"
	EndpointJamfProSSOCertV2                                 = "/api/v2/sso/cert"
	EndpointJamfProSSOCertDownloadV2                         = "/api/v2/sso/cert/download"
	EndpointJamfProSSOCertParseV2                            = "/api/v2/sso/cert/parse"
	EndpointJamfProSSOFailoverV1                             = "/api/v1/sso/failover"
	EndpointJamfProSSOFailoverGenerateV1                     = "/api/v1/sso/failover/generate"
	EndpointJamfProSsoV3                                     = "/api/v3/sso"
	EndpointJamfProDependenciesV3                            = "/api/v3/sso/dependencies"
	EndpointJamfProDisableV3                                 = "/api/v3/sso/disable"
	EndpointJamfProHistoryV3                                 = "/api/v3/sso/history"
	EndpointJamfProMetadataDownloadV3                        = "/api/v3/sso/metadata/download"
	EndpointJamfProStartupStatus                             = "/api/startup-status"
	EndpointJamfProStaticComputerGroups2V2                   = "/api/v2/computer-groups/static-groups"
	EndpointJamfProStaticMobileDeviceGroups2V2               = "/api/v2/mobile-device-groups/static-groups"
	EndpointJamfProTimeZonesV1                               = "/api/v1/time-zones"
	EndpointJamfProIssueTomcatSslCertificate                 = "/api/settings/issueTomcatSslCertificate"
	EndpointJamfProUser                                      = "/api/user"
	EndpointJamfProChangePasswordV1                          = "/api/v1/user/change-password"
	EndpointJamfProUpdateSession                             = "/api/user/updateSession"
	EndpointJamfProVenafiV1                                  = "/api/v1/pki/venafi"
	EndpointJamfProVolumePurchasingLocationsV1               = "/api/v1/volume-purchasing-locations"
	EndpointJamfProVolumePurchasingSubscriptionsV1           = "/api/v1/volume-purchasing-subscriptions"
)

// ComputerInventorySections contains all available sections for computer inventory API requests.
var ComputerInventorySections = []string{
	"GENERAL", "DISK_ENCRYPTION", "PURCHASING", "APPLICATIONS", "STORAGE",
	"USER_AND_LOCATION", "CONFIGURATION_PROFILES", "PRINTERS", "SERVICES",
	"HARDWARE", "LOCAL_USER_ACCOUNTS", "CERTIFICATES", "ATTACHMENTS",
	"PLUGINS", "PACKAGE_RECEIPTS", "FONTS", "SECURITY", "OPERATING_SYSTEM",
	"LICENSED_SOFTWARE", "IBEACONS", "SOFTWARE_UPDATES", "EXTENSION_ATTRIBUTES",
	"CONTENT_CACHING", "GROUP_MEMBERSHIPS",
}

// Dock item type constants
const (
	TypeApp    = "APP"
	TypeFile   = "FILE"
	TypeFolder = "FOLDER"
)

// Script priority values
const (
	ScriptPriorityBefore   = "BEFORE"
	ScriptPriorityAfter    = "AFTER"
	ScriptPriorityAtReboot = "AT_REBOOT"
)

// User interface display theme values
const (
	ThemeMatchSystem = "MATCH_SYSTEM"
	ThemeLight       = "LIGHT"
	ThemeDark        = "DARK"
)

// Search method values for computer, mobile device, and user search preferences
const (
	SearchExactMatch = "EXACT_MATCH"
	SearchStartsWith = "STARTS_WITH"
	SearchContains   = "CONTAINS"
)

// Application values for the application query parameter
const (
	ApplicationProtect = "protect"
	ApplicationConnect = "connect"
)
